/**
 * Sample products and SKU variants
 */
exports.seed = async function (knex) {
  await knex('skus').del();
  await knex('products').del();

  // ── Products ────────────────────────────────────────────────────────────────
  await knex('products').insert([
    {
      id: 1,
      name: 'TechCore ProBook 15',
      slug: 'techcore-probook-15',
      description: 'High-performance 15-inch laptop powered by the latest processor with long battery life.',
      category_id: 11,
      brand_id: 1,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 2,
      name: 'NovaMobile X12',
      slug: 'novamobile-x12',
      description: 'Flagship smartphone with a 6.7-inch AMOLED display and a 108 MP camera system.',
      category_id: 10,
      brand_id: 6,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 3,
      name: 'SoundWave ANC Pro Headphones',
      slug: 'soundwave-anc-pro-headphones',
      description: 'Over-ear active noise-cancelling headphones with 30-hour battery.',
      category_id: 12,
      brand_id: 5,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 4,
      name: 'UrbanWear Classic Tee',
      slug: 'urbanwear-classic-tee',
      description: '100% organic cotton classic-fit t-shirt available in multiple colours.',
      category_id: 20,
      brand_id: 2,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 5,
      name: 'HomeEssentials Chef Pan Set',
      slug: 'homeessentials-chef-pan-set',
      description: 'Non-stick 3-piece frying pan set suitable for all hob types.',
      category_id: 31,
      brand_id: 3,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 6,
      name: 'ActivePeak Trail Runner',
      slug: 'activepeak-trail-runner',
      description: 'Lightweight trail running shoe with superior grip and breathable mesh upper.',
      category_id: 40,
      brand_id: 4,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);

  // ── SKUs ─────────────────────────────────────────────────────────────────────
  await knex('skus').insert([
    // TechCore ProBook 15 — storage variants
    {
      id: 101,
      product_id: 1,
      sku_code: 'TCPB15-256-SLV',
      name: 'TechCore ProBook 15 — 256 GB Silver',
      price: 999.99,
      compare_at_price: 1199.99,
      cost_price: 650.00,
      stock_quantity: 25,
      attributes: JSON.stringify({ storage: '256 GB', colour: 'Silver' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 102,
      product_id: 1,
      sku_code: 'TCPB15-512-SLV',
      name: 'TechCore ProBook 15 — 512 GB Silver',
      price: 1199.99,
      compare_at_price: 1399.99,
      cost_price: 800.00,
      stock_quantity: 15,
      attributes: JSON.stringify({ storage: '512 GB', colour: 'Silver' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 103,
      product_id: 1,
      sku_code: 'TCPB15-512-BLK',
      name: 'TechCore ProBook 15 — 512 GB Space Black',
      price: 1199.99,
      compare_at_price: 1399.99,
      cost_price: 800.00,
      stock_quantity: 10,
      attributes: JSON.stringify({ storage: '512 GB', colour: 'Space Black' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // NovaMobile X12 — colour variants
    {
      id: 201,
      product_id: 2,
      sku_code: 'NVX12-128-BLK',
      name: 'NovaMobile X12 128 GB Midnight Black',
      price: 799.99,
      compare_at_price: 899.99,
      cost_price: 480.00,
      stock_quantity: 40,
      attributes: JSON.stringify({ storage: '128 GB', colour: 'Midnight Black' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 202,
      product_id: 2,
      sku_code: 'NVX12-128-WHT',
      name: 'NovaMobile X12 128 GB Pearl White',
      price: 799.99,
      compare_at_price: 899.99,
      cost_price: 480.00,
      stock_quantity: 35,
      attributes: JSON.stringify({ storage: '128 GB', colour: 'Pearl White' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 203,
      product_id: 2,
      sku_code: 'NVX12-256-BLK',
      name: 'NovaMobile X12 256 GB Midnight Black',
      price: 899.99,
      compare_at_price: 999.99,
      cost_price: 560.00,
      stock_quantity: 20,
      attributes: JSON.stringify({ storage: '256 GB', colour: 'Midnight Black' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // SoundWave ANC Pro Headphones — colour variants
    {
      id: 301,
      product_id: 3,
      sku_code: 'SWANCP-BLK',
      name: 'SoundWave ANC Pro — Black',
      price: 249.99,
      compare_at_price: 299.99,
      cost_price: 120.00,
      stock_quantity: 50,
      attributes: JSON.stringify({ colour: 'Black' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 302,
      product_id: 3,
      sku_code: 'SWANCP-WHT',
      name: 'SoundWave ANC Pro — White',
      price: 249.99,
      compare_at_price: 299.99,
      cost_price: 120.00,
      stock_quantity: 30,
      attributes: JSON.stringify({ colour: 'White' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // UrbanWear Classic Tee — size & colour variants
    {
      id: 401,
      product_id: 4,
      sku_code: 'UWCT-S-WHT',
      name: 'UrbanWear Classic Tee — S White',
      price: 24.99,
      compare_at_price: null,
      cost_price: 8.00,
      stock_quantity: 100,
      attributes: JSON.stringify({ size: 'S', colour: 'White' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 402,
      product_id: 4,
      sku_code: 'UWCT-M-WHT',
      name: 'UrbanWear Classic Tee — M White',
      price: 24.99,
      compare_at_price: null,
      cost_price: 8.00,
      stock_quantity: 150,
      attributes: JSON.stringify({ size: 'M', colour: 'White' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 403,
      product_id: 4,
      sku_code: 'UWCT-L-WHT',
      name: 'UrbanWear Classic Tee — L White',
      price: 24.99,
      compare_at_price: null,
      cost_price: 8.00,
      stock_quantity: 120,
      attributes: JSON.stringify({ size: 'L', colour: 'White' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 404,
      product_id: 4,
      sku_code: 'UWCT-M-BLK',
      name: 'UrbanWear Classic Tee — M Black',
      price: 24.99,
      compare_at_price: null,
      cost_price: 8.00,
      stock_quantity: 130,
      attributes: JSON.stringify({ size: 'M', colour: 'Black' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // HomeEssentials Chef Pan Set — single SKU
    {
      id: 501,
      product_id: 5,
      sku_code: 'HECPS-3PC',
      name: 'HomeEssentials Chef Pan Set — 3 Piece',
      price: 79.99,
      compare_at_price: 99.99,
      cost_price: 35.00,
      stock_quantity: 60,
      attributes: JSON.stringify({ pieces: 3 }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // ActivePeak Trail Runner — size variants
    {
      id: 601,
      product_id: 6,
      sku_code: 'APTR-UK8-GRN',
      name: 'ActivePeak Trail Runner — UK 8 Forest Green',
      price: 119.99,
      compare_at_price: 149.99,
      cost_price: 55.00,
      stock_quantity: 20,
      attributes: JSON.stringify({ size_uk: 8, colour: 'Forest Green' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 602,
      product_id: 6,
      sku_code: 'APTR-UK9-GRN',
      name: 'ActivePeak Trail Runner — UK 9 Forest Green',
      price: 119.99,
      compare_at_price: 149.99,
      cost_price: 55.00,
      stock_quantity: 18,
      attributes: JSON.stringify({ size_uk: 9, colour: 'Forest Green' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 603,
      product_id: 6,
      sku_code: 'APTR-UK10-GRN',
      name: 'ActivePeak Trail Runner — UK 10 Forest Green',
      price: 119.99,
      compare_at_price: 149.99,
      cost_price: 55.00,
      stock_quantity: 12,
      attributes: JSON.stringify({ size_uk: 10, colour: 'Forest Green' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 604,
      product_id: 6,
      sku_code: 'APTR-UK9-BLK',
      name: 'ActivePeak Trail Runner — UK 9 Stealth Black',
      price: 119.99,
      compare_at_price: 149.99,
      cost_price: 55.00,
      stock_quantity: 22,
      attributes: JSON.stringify({ size_uk: 9, colour: 'Stealth Black' }),
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);
};
